select top 10 * from customer 

--Q1. What is the total revenue generated by male vs female customer?
select gender,sum(purchase_amount_USD) from customer group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount_USD from customer where discount_applied='Yes' 
and purchase_amount_USD>(select avg(purchase_amount_USD) from customer) 

--Q3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased,avg(review_rating) as avg_r_r from customer group by item_purchased 
order by avg_r_r desc 

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,round(avg(purchase_amount_USD),2) from customer 
where shipping_type in('Express','Standard') group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,COUNT(subscription_status) AS TOTAL_CUSTOMERS,round(avg(purchase_amount_USD),2) as AVERAGE,sum(purchase_amount_USD)
AS TOTAL_AMOUNT from customer group by subscription_status 

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 ITEM_PURCHASED,ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as Discount_rate
FROM CUSTOMER GROUP BY ITEM_PURCHASED ORDER BY Discount_rate DESC;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id,previous_purchases,
CASE 
WHEN previous_purchases = 1 THEN 'New'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'Loyal'
END AS customer_segment
from customer
)
select customer_segment , count(*) as "Number of Customers"
from customer_type
group by customer_segment
--Q8. What are the top 3 most purchased products within each category?
--select item_purchased AS ITEM,Category from Customer group by ITEM,category order by COUNT(item_purchased) desc --limit 3

WITH ITEM_COUNTS AS (
Select category, item_purchased, COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders from ITEM_COUNTS where item_rank<=3; 

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers from customer where previous_purchases>5 group by subscription_status


--Q10. What is the revenue contribution of each age group?
select age_group,sum(purchase_amount_USD) from customer group by age_group













































































++